version: '3.4'

services:
  node_1:
    build:
      context: ../
      args:
        PROJECT: juno
        PROJECT_BIN: junod
        PROJECT_DIR: .juno
        VERSION: v1.0.0
        REPOSITORY: https://github.com/CosmosContracts/Juno
        NAMESPACE: JUNOD
        BUILD_ENV: juno
        WASMVM_VERSION: v0.14.0
    ports:
      - '26656:26656'
      - '26657:26657'
    environment:
      - MONIKER=node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/nullmames/juno-on-akash/main/chain.json
      - SNAPSHOT_JSON=https://cosmos-snapshots.s3.filebase.com/juno/snapshot.json
    env_file:
      - ../.env
    volumes:
      - ./node-data:/root/.juno
