version: '3.4'

services:
  node_1:
    image: ghcr.io/ovrclk/cosmos-omnibus:v0.2.7-juno-v9.0.0
    ports:
      - '26656:26656'
      - '26657:26657'
      - '1317:1317'
    environment:
      - MONIKER=node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/juno/chain.json
      - GENESIS_URL=https://download.dimi.sh/juno-phoenix2-genesis.tar.gz
      - GENESIS_FILENAME=juno-phoenix2-genesis.json
      - P2P_POLKACHU=1
      # - STATESYNC_POLKACHU=1
      - SNAPSHOT_POLKACHU=1
    volumes:
      - ./node-data:/root/.juno
