version: '3.4'

services:
  node_1:
    build:
      context: ../
      args:
        PROJECT: gaia
        PROJECT_BIN: gaiad
        VERSION: v4.2.1
        REPOSITORY: https://github.com/cosmos/gaia
    environment:
      - MONIKER=gaia_node_1
      - PROJECT_DIR=.gaia
      - CHAIN_ID=cosmoshub-4
      - SEED_NODES=bf8328b66dceb4987e5cd94430af66045e59899f@public-seed.cosmos.vitwit.com:26656,cfd785a4224c7940e9a10f6c1ab24c343e923bec@164.68.107.188:26656,d72b3011ed46d783e369fdf8ae2055b99a1e5074@173.249.50.25:26656,ba3bacc714817218562f743178228f23678b2873@public-seed-node.cosmoshub.certus.one:26656,3c7cad4154967a294b3ba1cc752e40e8779640ad@84.201.128.115:26656,366ac852255c3ac8de17e11ae9ec814b8c68bddb@51.15.94.196:26656
      - GENESIS_URL=https://github.com/cosmos/mainnet/raw/master/genesis.cosmoshub-4.json.gz
      - DENOM=uatom
      - NAMESPACE=GA
    volumes:
      - ./node-data:/root/.gaia
