version: '3.4'

services:
  node_1:
    image: ghcr.io/ovrclk/cosmos-omnibus:v0.3.11-dig-v3.3.1
    ports:
      - '26656:26656'
      - '26657:26657'
      - '1317:1317'
    environment:
      - MONIKER=node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/dig/chain.json
    volumes:
      - ./node-data:/root/.dig
