version: '3.4'

services:
  node_1:
    build:
      context: ../
      args:
        PROJECT: kava
        PROJECT_BIN: kvd
        VERSION: v0.14.2
        REPOSITORY: https://github.com/Kava-Labs/kava
        NAMESPACE: KA
    ports:
      - '26657:26657'
    environment:
      - MONIKER=node_1
      - CHAIN_URL=https://raw.githubusercontent.com/sikkatech/tm-networks/master/kava-7/chain.json
      - MINIMUM_GAS_PRICES=0.025ukava
    volumes:
      - ./node-data:/root/.kvd
