version: '3.4'

services:
  node_1:
    build:
      context: ../
      args:
        PROJECT: akash
        VERSION: v0.12.1
        BUILD_ENV: custom_image
        BUILD_IMAGE: ghcr.io/ovrclk/akash:0.12.1
    environment:
      - MONIKER=node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/ovrclk/net/master/mainnet/meta.json
      - SNAPSHOT_JSON=https://cosmos-snapshots.s3.filebase.com/akash/snapshot.json
      - MINIMUM_GAS_PRICES=0.025uakt
      - FASTSYNC_VERSION=v2
    env_file:
      - ../.env
    volumes:
      - ./node-data:/root/.akash
