version: '3.4'

services:
  node_1:
    build:
      context: ../
      args:
        PROJECT: sentinelhub
        VERSION: v0.8.3
        REPOSITORY: https://github.com/sentinel-official/hub.git
    ports:
      - '26656:26656'
      - '26657:26657'
    environment:
      - MONIKER=node_1
      - CHAIN_URL=https://raw.githubusercontent.com/cosmos/chain-registry/master/sentinel/chain.json
      - VALIDATE_GENESIS=0 # failing currently?
    env_file:
      - ../.env
    volumes:
      - ./node-data:/root/.sentinelhub
