version: '3.4'

services:
  node_1:
    image: ghcr.io/akash-network/cosmos-omnibus:v0.4.33-teritori-v2.0.6
    ports:
      - '26656:26656'
      - '26657:26657'
      - '1317:1317'
    environment:
      - MONIKER=node_1
      - CHAIN_ID=teritori-1
      - GENESIS_URL=https://github.com/TERITORI/teritori-mainnet-genesis/raw/main/genesis.json
      - P2P_POLKACHU=1
      - STATESYNC_POLKACHU=1
    volumes:
      - ./node-data:/root/.teritorid
