version: '3.4'

services:
  node_1:
    build:
      context: ../
      args:
        PROJECT: osmosis
        PROJECT_BIN: osmosisd
        VERSION: v6.0.0
        REPOSITORY: https://github.com/osmosis-labs/osmosis
        NAMESPACE: OSMOSISD
        GOLANG_VERSION: 1.17-buster
    ports:
      - '26656:26656'
      - '26657:26657'
    environment:
      - MONIKER=node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/chain.json
      - VALIDATE_GENESIS=0
      - SNAPSHOT_JSON=https://cosmos-snapshots.s3.filebase.com/osmosis/snapshot.json
    env_file:
      - ../.env
    volumes:
      - ./node-data:/root/.osmosisd
