version: '3.4'

services:
  node_1:
    image: ghcr.io/akash-network/cosmos-omnibus:v0.3.51-osmosis-v19.0.0
    ports:
      - '26656:26656'
      - '26657:26657'
      - '1317:1317'
    environment:
      - MONIKER=node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/chain.json
      - P2P_POLKACHU=1
      - STATESYNC_POLKACHU=1
      #- SNAPSHOT_WASM_PATH=wasm
      ## Make sure to set SNAPSHOT_DATA_PATH=data when using snapshots with the directory structure // TODO: https://github.com/akash-network/cosmos-omnibus/issues/378
      # - SNAPSHOT_URL=https://snapshots.polkachu.com/snapshots/osmosis/osmosis_7268027.tar.lz4
      # - SNAPSHOT_DATA_PATH=data
      ## You can use state-sync instead of downloading the snapshot archive
      # - STATESYNC_RPC_SERVERS=https://rpc-osmosis-ia.cosmosia.notional.ventures:443,https://osmosis-rpc.polkachu.com:443,https://osmosis.validator.network:443,https://rpc-osmosis.blockapsis.com:443
    volumes:
      - ./node-data:/root/.osmosisd
