version: '3.4'

services:
  node_1:
    build:
      context: ../
      args:
        PROJECT: osmosis
        PROJECT_BIN: osmosisd
        VERSION: v4.1.0
        REPOSITORY: https://github.com/osmosis-labs/osmosis
        NAMESPACE: OSMOSISD
    ports:
      - '26656:26656'
      - '26657:26657'
    environment:
      - MONIKER=node_1
      - CHAIN_URL=https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/chain.json
      - VALIDATE_GENESIS=0 # failing currently
    env_file:
      - ../.env
    volumes:
      - ./node-data:/root/.osmosisd
