version: '3.4'

services:
  node_1:
    build:
      context: ../
      args:
        PROJECT: iris
        PROJECT_BIN: iris
        VERSION: v1.0.1
        REPOSITORY: https://github.com/irisnet/irishub
        NAMESPACE: IRIS
    ports:
      - '26656:26656'
      - '26657:26657'
    environment:
      - MONIKER=node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/betterclever/chain-registry/update-irishub-config/irisnet/chain.json
      - VALIDATE_GENESIS=0
    env_file:
      - ../.env
    volumes:
      - ./node-data:/root/.iris