version: '3.4'

services:
  node_1:
    image: ghcr.io/ovrclk/cosmos-omnibus:v0.0.27-bitcanna-v.1.3.1
    ports:
      - '26656:26656'
      - '26657:26657'
      - '1317:1317'
    environment:
      - MONIKER=node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/bitcanna/chain.json
      - SNAPSHOT_JSON=https://cosmos-snapshots.s3.filebase.com/bitcanna/snapshot.json
    env_file:
      - ../.env
    volumes:
      - ./node-data:/root/.bcna
