version: '3.4'

services:
  node_1:
    build:
      context: ../
      args:
        PROJECT: bitcanna
        PROJECT_BIN: bcnad
        PROJECT_DIR: .bcna
        VERSION: v1.2
        REPOSITORY: https://github.com/BitCannaGlobal/bcna
        NAMESPACE: BCNAD
        WASMVM_VERSION: v0.14.0
    ports:
      - '26656:26656'
      - '26657:26657'
    environment:
      - MONIKER=node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/bitcanna/chain.json
    env_file:
      - ../.env
    volumes:
      - ./node-data:/root/.bcna
