version: '3.4'

services:
  node_1:
    image: ghcr.io/ovrclk/cosmos-omnibus:v0.1.1-terra-v0.5.18
    ports:
      - '26656:26656'
      - '26657:26657'
      - '1317:1317'
    environment:
      - MONIKER=node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/terra/chain.json
      - SNAPSHOT_QUICKSYNC=https://quicksync.io/terra.json
    volumes:
      - ./node-data:/root/.terra
