version: '3.4'

services:
  node_1:
    image: ghcr.io/ovrclk/cosmos-omnibus:v0.1.2-thorchain-chaosnet-multichain
    ports:
      - '1317:1317' # api
      - '27146:27146' # p2p
      - '27147:27147' #rpc
    environment:
      - MONIKER=node_1
      - CHAIN_ID=thorchain
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/thorchain/chain.json
      - OVERWRITE_SEEDS=1
    volumes:
      - ./node-data:/root/.thornode
