version: '3.4'

services:
  node_1:
    image: ghcr.io/ovrclk/cosmos-omnibus:v0.3.19-evmos-v10.0.1
    ports:
      - '26656:26656'
      - '26657:26657'
      - '1317:1317'
    environment:
      - MONIKER=node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/evmos/chain.json
      - P2P_POLKACHU=1
      # - STATESYNC_POLKACHU=1
      - SNAPSHOT_POLKACHU=1
    volumes:
      - ./node-data:/root/.evmosd
