version: '3.4'

services:
  node_1:
    build:
      context: ../
      args:
        PROJECT: thornode
        PROJECT_BIN: thornode
        PROJECT_DIR: .thornode
        VERSION: chaosnet-multichain
        REPOSITORY: https://gitlab.com/thorchain/thornode
        NAMESPACE: THOR
        GOLANG_VERSION: 1.17-buster
        APT_INSTALL_EXTRA_DEPS: protobuf-compiler
        MAKE_ENV: "TAG=mainet BUILD_TAG=mainet"
    ports:
      - '1317:1317' # api
      - '27146:27146' # p2p
      - '27147:27147' #rpc
    environment:
      - MONIKER=node_1
      - CHAIN_ID=thorchain
      - CHAIN_JSON=https://raw.githubusercontent.com/marius-avram/chain-registry/thornode/thornode/chain.json
    env_file:
      - ../.env
    volumes:
      - ./node-data:/root/.thornode
