version: '3.4'

services:
  node_1:
    image: ghcr.io/akash-network/cosmos-omnibus:v0.4.20-seinetwork-v3.9.0
    ports:
      - '26656:26656'
      - '26657:26657'
      - '1317:1317'
    environment:
      - MONIKER=node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/sei/chain.json
      - P2P_POLKACHU=1
      - FASTSYNC_VERSION=v0
    volumes:
      - ./node-data:/root/.sei
