version: '3.4'

services:
  node_1:
    image: ghcr.io/ovrclk/cosmos-omnibus:v0.0.25-emoney-v1.1.3
    ports:
      - '26656:26656'
      - '26657:26657'
      - '1317:1317'
    environment:
      - MONIKER=node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/emoney/chain.json
      - VALIDATE_GENESIS=0
    volumes:
      - ./node-data:/root/.emd
