version: '3.4'

services:
  node_1:
    image: ghcr.io/akash-network/cosmos-omnibus:v0.4.5-cryptoorgchain-v4.2.8
    ports:
      - '26656:26656'
      - '26657:26657'
      - '1317:1317'
    environment:
      - MONIKER=node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/cryptoorgchain/chain.json
      - SNAPSHOT_QUICKSYNC=https://quicksync.io/crypto.json
    volumes:
      - ./node-data:/root/.chain-maind
