version: '3.4'

services:
  node_1:
    image: ghcr.io/ovrclk/cosmos-omnibus:v0.0.23-sifchain-v0.10.1
    ports:
      - '26656:26656'
      - '26657:26657'
      - '1317:1317'
    environment:
      - MONIKER=node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/sifchain/chain.json
      - VALIDATE_GENESIS=0
      - SNAPSHOT_JSON=https://cosmos-snapshots.s3.filebase.com/sifchain/snapshot.json
    volumes:
      - ./node-data:/root/.sifnoded
