version: '3.4'

services:
  node_1:
    image: ghcr.io/akash-network/cosmos-omnibus:v0.3.51-generic
    ports:
      - '26656:26656'
      - '26657:26657'
      - '1317:1317'
    environment:
      - MONIKER=node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/akash-network/net/main/edgenet/meta.json
      - BINARY_ZIP_PATH=akash_0.15.0-rc14_linux_amd64/akash
    volumes:
      - ./node-data:/root/.akash
